#!/usr/bin/env node

// try {
//     require.resolve('@tiger/cli');
// } catch (err) {
//     throw new Error('未安装 @tiger/cli 依赖');
// }

// eslint-disable-next-line @typescript-eslint/no-var-requires
const daze = require('../packages/cli/dist');

daze.terminate(process.argv);
