import * as symbols from '../symbol';
import { createInjectDecorator } from './factory/create-inject-decorator';

export const OriginalReq = createInjectDecorator(symbols.INJECTORS.REQ);
export const Req = OriginalReq;
export const originalReq = OriginalReq;
export const req = OriginalReq;
export const OriginalRes = createInjectDecorator(symbols.INJECTORS.RES);
export const Res = OriginalRes;
export const originalRes = OriginalReq;
export const res = OriginalReq;
export const Request = createInjectDecorator(symbols.INJECTORS.REQUEST);
export const request = Request;
export const Response = createInjectDecorator(symbols.INJECTORS.RESPONSE);
export const response = Response;
export const Query = createInjectDecorator(symbols.INJECTORS.QUERY);
export const query = Query;
export const Params = createInjectDecorator(symbols.INJECTORS.PARAMS);
export const params = Params;
export const Header= createInjectDecorator(symbols.INJECTORS.HEADERS);
export const header = Header;
export const Headers = Header;
export const headers = Header;
export const Body = createInjectDecorator(symbols.INJECTORS.BODY);
export const body = Body;
export const CookieValue = createInjectDecorator(symbols.INJECTORS.COOKIE);
export const cookieValue = CookieValue;
export const SessionValue = createInjectDecorator(symbols.INJECTORS.SESSION);
export const sessionValue = SessionValue;
